### ISSUE TITLE
Didn't set ElevatorSlave as a Follower of Elevator

### ISSUE THREAD

**Issue by Sanjana679** [2643/2019-Code#7]
ElevatorSlave was never set as a Follower of Elevator. It would be done as so: 

```
 ElevatorSlave.set(ControlMode.Follower, Elevator.getDeviceID()); 
```
Since you are setting the ElevatorSlave as a Follower of Elevator, you don't need to set the speed of the ElevatorSlave as you have done in line 35, line 41, and line 47 in Elevator.java.

**Comment by probablyanasian** [comment]
Issue should be fixed.
