### ISSUE TITLE
Unnecessary to have three speed methods 

### ISSUE THREAD

**Issue by Sanjana679** [2643/2019-Code#8]
It is not necessary to have three methods to set the speed of the motors in Elevator.java. 

You could do this:
```
public void setSpeed(double speed){
    Elevator.set(speed);
}
```

instead of `setNegativeSpeed(double speed)`, `setPositiveSpeed(double speed)`, and `setZeroSpeed(double speed)`

**Comment by probablyanasian** [comment]
Issue Resolved.
